trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/
    - azure-pipelines/release.yml

parameters:
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  codecov_token: 38462e91-92d5-4fa6-be55-f363099a3e15
  ci_feed: https://pkgs.dev.azure.com/andrewarnott/OSS/_packaging/PublicCI/nuget/v3/index.json
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/
  CARGO_HOME: $(Agent.TempDirectory)/.cargo

jobs:
- template: azure-pipelines/build.yml
  parameters:
    RunTests: ${{ parameters.RunTests }}
