trigger:
  batch: true
  branches:
    include:
    - main
    - app
    - app-prerelease
    - app-release
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/
    - azure-pipelines/release.yml

parameters:
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/

jobs:
- template: azure-pipelines/build.yml
  parameters:
    RunTests: ${{ parameters.RunTests }}
    # Allowed values for GooglePlayTrack: internal, alpha, beta, production
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/app') }}:
      BaseChannelName: dogfood
      GooglePlayTrack: internal
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/app-prerelease') }}:
      BaseChannelName: prerelease
      GooglePlayTrack: alpha
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/app-release') }}:
      BaseChannelName: release
      GooglePlayTrack: production
    signArtifacts: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
