parameters:
- name: test_target

steps:
- task: Cache@2
  inputs:
    key: '"cargo" | "$(Agent.OS)"' # | src/nerdbank-zcash-rust/cargoTomlTargets/**/Cargo.lock'
    path: $(Build.SourcesDirectory)/src/nerdbank-zcash-rust/target
  displayName: 🧠 cache cargo build
# - task: Cache@2
#   inputs:
#     key: '"cargo-registry" | "$(Agent.OS)"' # | src/nerdbank-zcash-rust/cargoTomlTargets/**/Cargo.lock'
#     path: $(HOME)/.cargo/registry
#   displayName: cache cargo registry

- pwsh: src/nerdbank-zcash-rust/build_all.ps1 -Release
  displayName: 🛠️ cargo build
- pwsh: cargo test -r --target ${{ parameters.test_target }}
  displayName: 🧪 cargo test
  workingDirectory: src/nerdbank-zcash-rust
  env:
    RUST_BACKTRACE: 1
  condition: and(succeeded(), ne('${{ parameters.test_target }}', ''))
- pwsh:  cargo clippy
  displayName: 🧼 cargo clippy
  workingDirectory: src/nerdbank-zcash-rust
