parameters:
- name: test_target
- name: checks
  type: boolean
  default: false

steps:
- task: Cache@2
  inputs:
    key: '"cargo" | "$(Agent.OS)"'
    path: $(Build.SourcesDirectory)/src/nerdbank-zcash-rust/target
  displayName: 🧠 cache cargo build
- task: Cache@2
  inputs:
    key: '"cargo-registry" | "$(Agent.OS)"'
    path: $(HOME)/.cargo/registry
  displayName: 🧠 cache cargo registry

- pwsh: src/nerdbank-zcash-rust/build_all.ps1 -Release
  displayName: 🛠️ cargo build

- pwsh: cargo test -r --target ${{ parameters.test_target }}
  displayName: 🧪 cargo test
  workingDirectory: src/nerdbank-zcash-rust
  env:
    RUST_BACKTRACE: 1
  condition: and(succeeded(), ne('${{ parameters.test_target }}', ''))
  continueOnError: true # too many tests fail with network errors

- ${{ if parameters.checks }}:
  - pwsh: cargo clippy -- -D warnings
    displayName: 🧼 cargo clippy
    workingDirectory: src/nerdbank-zcash-rust

  - pwsh: cargo fmt --check
    displayName: 📝 cargo fmt
    workingDirectory: src/nerdbank-zcash-rust
