parameters:
- name: RunTests
  type: boolean
- name: osRID
  type: string
- name: publishPlatforms
  type: object
- name: AppleStoreReady
  type: boolean

steps:

- pwsh: dotnet build -t:build,publish --no-restore -c $(BuildConfiguration) -warnaserror /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  displayName: 🛠️ dotnet build
  workingDirectory: azure-pipelines
  env:
    DisableAndroidCsproj: true # We only want to build the android project in the Pack job

- powershell: azure-pipelines/dotnet-test-cloud.ps1 -Configuration $(BuildConfiguration) -Agent $(Agent.JobName) -PublishResults
  displayName: 🧪 dotnet test
  condition: and(succeeded(), ${{ parameters.RunTests }})

- ${{ if and(parameters.AppleStoreReady, eq(parameters.osRID, 'osx')) }}:
  - bash: xcrun altool --validate-app -f "bin/Nerdbank.Zcash.App.iOS/Release/net8.0-ios18.0/ios-arm64/publish/Nerdbank.Zcash.App.iOS.ipa" -t ios -u $(APPLE-ID) -p $(APPLE-PASSWORD)
    displayName: 🧪 Validate iOS app
    condition: and(succeeded(), ${{ parameters.RunTests }})

- powershell: azure-pipelines/variables/_pipelines.ps1
  failOnStderr: true
  displayName: ⚙ Update pipeline variables based on build outputs
  condition: succeededOrFailed()

- powershell: azure-pipelines/artifacts/_pipelines.ps1 -ArtifactNameSuffix "-$(Agent.JobName)" -Verbose
  failOnStderr: true
  displayName: 📢 Publish artifacts
  condition: succeededOrFailed()

- ${{ if and(ne(variables['codecov_token'], ''), parameters.RunTests) }}:
  - powershell: |
      $ArtifactStagingFolder = & "azure-pipelines/Get-ArtifactsStagingDirectory.ps1"
      $CoverageResultsFolder = Join-Path $ArtifactStagingFolder "coverageResults-$(Agent.JobName)"
      azure-pipelines/publish-CodeCov.ps1 -CodeCovToken "$(codecov_token)" -PathToCodeCoverage "$CoverageResultsFolder" -Name "$(Agent.JobName) Coverage Results" -Flags "$(Agent.JobName)Host,$(BuildConfiguration)"
    displayName: 📢 Publish code coverage results to codecov.io
    timeoutInMinutes: 3
    continueOnError: true
